name: Feature request
description: Propose a new enhancement
labels: ["enhancement", "triage"]
body:
  - type: input
    id: summary
    attributes:
      label: Feature summary
      description: One-line value statement
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: User problem
      description: What user pain are we solving?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Suggested UX and behavior
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bullet list of testable outcomes
    validations:
      required: true
